buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Esta versión 8.5.0 es la medicina para el error HasConvention
        classpath 'com.android.tools.build:gradle:8.5.0'
        // Kotlin 1.9.22 para máxima estabilidad con Gradle 9
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
